#!/usr/bin/env python3
"""Generate the C endpoint header for odrive_lib from an ODrive flat_endpoints.json.

The ODrive exposes its config parameters over CAN (RxSdo/TxSdo) by numeric
*endpoint id*. Those ids come from the firmware's ``flat_endpoints.json`` and
change with every firmware/hardware build, so odrive_lib does not hardcode them
by hand -- this script reads the json and emits ``odrive_endpoints_0_6.h``, the
table the C library consumes for the periodic-message-rate API.

Usage:
    python tools/gen_endpoints.py flat_endpoints.json
    python tools/gen_endpoints.py flat_endpoints.json -o include/odrive_endpoints_0_6.h
    python tools/gen_endpoints.py flat_endpoints.json --fw-version 0.6.11

The json is obtained from your own ODrive (odrivetool caches it, or fetch it for
your firmware build). Endpoint ids are only valid for the matching firmware.
"""

import argparse
import json
import sys
from typing import Optional

# Firmware ``axis0.config.can.<leaf>`` parameter -> odrive_msg_rate_t constant.
# Order here is only for readable output; the emitted header uses designated
# initializers, so it is robust to the enum's declaration order.
RATE_PARAMS = [
    ("version_msg_rate_ms",     "ODRIVE_MSG_RATE_VERSION"),
    ("heartbeat_msg_rate_ms",   "ODRIVE_MSG_RATE_HEARTBEAT"),
    ("encoder_msg_rate_ms",     "ODRIVE_MSG_RATE_ENCODER"),
    ("iq_msg_rate_ms",          "ODRIVE_MSG_RATE_IQ"),
    ("error_msg_rate_ms",       "ODRIVE_MSG_RATE_ERROR"),
    ("temperature_msg_rate_ms", "ODRIVE_MSG_RATE_TEMPERATURE"),
    ("bus_voltage_msg_rate_ms", "ODRIVE_MSG_RATE_BUS_VOLTAGE"),
    ("torques_msg_rate_ms",     "ODRIVE_MSG_RATE_TORQUES"),
    ("powers_msg_rate_ms",      "ODRIVE_MSG_RATE_POWERS"),
]


def load_endpoints(path: str) -> tuple[dict, Optional[str]]:
    """Return (endpoints_dict, fw_version_str_or_None) from a flat_endpoints.json."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Top level is usually {"endpoints": {...}, "fw_version": "..."} but some
    # dumps are just the flat {path: {...}} map -- accept both.
    endpoints = data.get("endpoints", data) if isinstance(data, dict) else None
    if not isinstance(endpoints, dict):
        sys.exit(f"error: {path}: no 'endpoints' object found")

    version = None
    if isinstance(data, dict):
        for key in ("fw_version", "version", "firmware_version"):
            if key in data and data[key]:
                v = data[key]
                # version may be "0.6.11" or [0, 6, 11]
                version = ".".join(str(x) for x in v) if isinstance(v, list) else str(v)
                break
    return endpoints, version


def find_endpoint(endpoints: dict, leaf: str) -> Optional[dict]:
    """Find the endpoint entry whose path is the CAN config <leaf>.

    Matches ``*.config.can.<leaf>``; if several axes match, prefers axis0.
    """
    suffix = ".config.can." + leaf
    matches = [p for p in endpoints if p.endswith(suffix) or p == leaf]
    if not matches:
        return None
    matches.sort(key=lambda p: (0 if "axis0" in p else 1, p))
    entry = endpoints[matches[0]]
    entry = dict(entry)
    entry["_path"] = matches[0]
    return entry


def derive_major_minor(version: Optional[str]) -> tuple[int, int]:
    if not version:
        sys.exit("error: firmware version not found in json; pass --fw-version X.Y.Z")
    parts = version.strip().lstrip("vV").split(".")
    try:
        return int(parts[0]), int(parts[1])
    except (IndexError, ValueError):
        sys.exit(f"error: cannot parse major.minor from version '{version}'; "
                 f"pass --fw-version X.Y.Z")


def build_header(endpoints: dict, version: str) -> str:
    major, minor = derive_major_minor(version)
    rows = []
    n_found = 0
    for leaf, enum_name in RATE_PARAMS:
        entry = find_endpoint(endpoints, leaf)
        if entry is None:
            print(f"warning: '{leaf}' not found -> emitting 0 (unpopulated)",
                  file=sys.stderr)
            rows.append((enum_name, 0, f"{leaf}: NOT FOUND"))
            continue
        eid = int(entry["id"])
        etype = entry.get("type", "?")
        if eid > 0xFFFF:
            sys.exit(f"error: '{leaf}' id {eid} exceeds uint16 endpoint range")
        if etype not in ("uint32", "int32"):
            print(f"warning: '{leaf}' type is '{etype}', expected uint32",
                  file=sys.stderr)
        rows.append((enum_name, eid, f"{entry['_path']}  ({etype})"))
        n_found += 1

    if n_found == 0:
        sys.exit("error: no msg-rate endpoints found in json -- wrong file?")

    lines = []
    lines.append("/* AUTO-GENERATED by tools/gen_endpoints.py -- DO NOT EDIT BY HAND.")
    lines.append(f" * Source firmware: {version}")
    lines.append(" * Endpoint ids are only valid for this exact firmware build;")
    lines.append(" * regenerate from your device's flat_endpoints.json if it differs. */")
    lines.append("#ifndef ODRIVE_ENDPOINTS_0_6_H_")
    lines.append("#define ODRIVE_ENDPOINTS_0_6_H_")
    lines.append("")
    lines.append('#include "odrive_protocol.h"')
    lines.append("")
    lines.append(f"#define ODRIVE_FW_EXPECTED_MAJOR   {major}u")
    lines.append(f"#define ODRIVE_FW_EXPECTED_MINOR   {minor}u")
    lines.append(f'#define ODRIVE_FW_ENDPOINTS_BUILD  "{version}"')
    lines.append("")
    lines.append("/* SDO endpoint id per cyclic-message rate parameter (0 = unpopulated). */")
    lines.append("static const uint16_t ODRIVE_MSG_RATE_ENDPOINT[ODRIVE_MSG_RATE_COUNT] = {")
    width = max(len(name) for name, _, _ in rows)
    for enum_name, eid, comment in rows:
        lines.append(f"    [{enum_name:<{width}}] = {eid}u,  /* {comment} */")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* ODRIVE_ENDPOINTS_0_6_H_ */")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("json", help="path to flat_endpoints.json")
    ap.add_argument("-o", "--output", default="include/odrive_endpoints_0_6.h",
                    help="output header path (default: include/odrive_endpoints_0_6.h)")
    ap.add_argument("--fw-version",
                    help="override firmware version string (e.g. 0.6.11) if the "
                         "json has none")
    args = ap.parse_args()

    endpoints, version = load_endpoints(args.json)
    version = args.fw_version or version

    header = build_header(endpoints, version)
    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        f.write(header)
    print(f"wrote {args.output} (fw {version})")


if __name__ == "__main__":
    main()
